site_name: "MTUOC: A Practical Course on Machine Translation Technologies"
site_description: An open online course on machine translation technologies with MTUOC
site_author: Antoni Oliver and Sergi Alvarez-Vidal

theme:
  name: material
  features:
    - navigation.top
    - search.highlight
    - search.suggest
    - content.code.copy
 
  - Module 1. Deployment, Integration and Evaluation:
# INICI_WIKI_MODUL_1
# FINAL_WIKI_MODUL_1

  - Module 2. Corpus Engineering:
      - Overview: module-2/index.md

  - Module 3. NMT Training and Fine-tuning:
      - Overview: module-3/index.md

  - Module 4. LLMs for Translation:
      - Overview: module-4/index.md

  - Final project: final-project.md
  - Glossary: glossary.md
  - Troubleshooting: troubleshooting.md
  - References: references.md
  - Credits and licence: credits.md

markdown_extensions:
  - admonition
  - toc:
      permalink: true
  - tables
  - fenced_code
  - attr_list
  
extra_css:

  - stylesheets/extra.css
