name: Deploy Web to GitHub Pages

on:
  push:
    branches:
      - main  # S'executarà cada cop que pugis canvis a main
  workflow_run:
    workflows: ["Sincronització Automàtica Mòdul 1 (Wiki Externa)"] # <-- CANVIAT PERQUÈ COINCIDEIXI EXACTAMENT
    types:
      - completed # S'executarà automàticament quan el bot de la Wiki acabi!

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    # Només s'executa si el push és normal, o si el workflow_run s'ha completat AMB ÈXIT (success)
    if: ${{ github.event_name == 'push' || github.event.workflow_run.conclusion == 'success' }}
    steps:
      - uses: actions/checkout@v4

      - name: Configure Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.x

      - name: Install dependencies
        run: |
          pip install mkdocs mkdocs-material mkdocs-awesome-pages-plugin

      - name: Deploy to GitHub Pages
        run: |
          mkdocs gh-deploy --force
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
